# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_img1', models.CharField(max_length=100)),
                ('big_img2', models.CharField(max_length=100)),
                ('small_img1', models.CharField(max_length=100)),
                ('small_img2', models.CharField(max_length=100)),
                ('small_img3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='goodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('old_price', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lbtx1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lbty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=256)),
                ('portrait', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='warpy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods_img',
            name='s_img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.goodsDetail'),
        ),
    ]
