# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goodsDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserInfo')),
            ],
        ),
    ]
