# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_warpy'),
    ]

    operations = [
        migrations.CreateModel(
            name='goodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('old_price', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('cart', models.CharField(max_length=20)),
            ],
        ),
    ]
