# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_img1', models.CharField(max_length=100)),
                ('big_img2', models.CharField(max_length=100)),
                ('small_img1', models.CharField(max_length=100)),
                ('small_img2', models.CharField(max_length=100)),
                ('small_img3', models.CharField(max_length=100)),
                ('s_img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.goodsDetail')),
            ],
        ),
    ]
