# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_goods_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
